kind = "api"
previewPath = "/api"
title = "Bot de Música Telegram"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 8080
name = "API Server"
paths = ["/"]

[services.development]
run = "cd /home/runner/workspace && python3 main.py"

[services.production]

[services.production.run]
args = ["python3", "/home/runner/workspace/main.py"]
